version: 2


jobs:
  build:
    docker:
      - image: circleci/python:2.7

    steps:
      - add_ssh_keys
      - checkout

      - run:
        name: Execute Unit Tests
        command: python setup.py test

      - run:
          name: Upload Coverage
          command:
              | pip install coveralls
              | coveralls
